FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y \
    cmake ninja-build git pkg-config g++ ccache python3 python3-pip \
    flex bison nasm

RUN pip3 install meson

RUN git clone -b 1.22.6 https://gitlab.freedesktop.org/gstreamer/gstreamer.git  

RUN cd gstreamer && \
    meson setup build/ && \
    meson compile -C build/ && \
    meson install -C build/

ENV LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu/:/usr/local/lib/x86_64-linux-gnu/gstreamer-1.0